---
version: '3.5'

services:
  schema:
    tty: true 
    command: 'bundle exec foreman start'
    build:
      context: ./schema
    ports:
      - 5000:5000
    volumes:
      - ./schema:/schema
      - ./schema/.bundle:/schema/bundle
    environment:
      - RUBYOPT=-W0 -KU -E utf-8:utf-8

  server:
    build:
      context: ./server
    volumes:
      - ./server:/server
      - /server/node_modules
    ports:
      - 1234:1234
  client:
    build:
      context: ./client
    image: webpack
    links:
      - server
    ports:
      - 3000:3000
    volumes:
      - ./client:/client
      - /client/node_modules
