source 'https://rubygems.org'

gem 'rake'
gem 'rerun'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'thin'
gem 'foreman'
gem "sinatra-cross_origin", "~> 0.3.1"

group :development do
  gem 'guard'
  gem 'guard-rake'
  gem 'guard-shotgun'
  gem 'rb-fsevent'
end

group :test do
  gem 'rubocop'
end
